spring:
  application:
    name: agendapro-challenge
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
basic:
  auth:
    username: agendapro
    password: hello